services:
  chat-service:
    container_name: chat-service
    build:
      dockerfile: Dockerfile
    ports:
      - "19050:19050"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgsg-db:5432/${DB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - pgsg-network


networks:
  pgsg-network:
    external: true