server:
  port: 11000

spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_URL:localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.ai.tool: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG


monitoring:
  prometheus: 
    url: ${PROMETHEUS_URL:http://localhost:4101}
  loki:
    url: ${LOKI_URL:http://localhost:4102}
