server:
  port: 10003

spring:
#  cloud:
#    gcp:
#      storage:
#        enabled: true
#        bucket: ${GCS_BUCKET_NAME}
#      credentials:
#        location: ${GCP_CREDENTIAL_LOCATION}
#      project-id: ${GCP_PROJECT_ID}
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL:localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    open-in-view: false
    generate-ddl: true

  servlet:
    multipart:
      max-file-size: 10MB # 파일 한개당 최대 사이즈
      max-request-size: 50MB # 전체 업로드 파일 최대 사이즈
      file-size-threshold: 20MB # 파일 업로드 -> 임시메모리 생성 -> 파일을 이동(local, s3, gcs) // 임시 메모리에 저장하는 것은 20MB 이하, 이상 -> 임시 폴더 저장(/tmp)


# 로그 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace


# 파일 설정
file:
  storage:
    type: local # local, s3, gcs
    endpoint: ${STORAGE_ENDPOINT}

  local:
    base:
      path: ${FILE_BASE_PATH:./storage/files}
      url: ${FILE_BASE_URL:/upload/}
  s3:
    bucket: sparta-bucket
    region: ap-northeast-2
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}

